target-version = "py312"
line-length = 100
extend-exclude = ["build", "dist", ".venv", ".uv", "result", "__pycache__"]

[lint]
select = ["E", "F", "W", "I", "B", "UP", "SIM", "PL", "Q", "RET", "TRY"]
ignore = ["E501"]
per-file-ignores = { "tests/**/*.py" = ["S101", "PLR2004"] }

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"
